# config.yml

CSV_FILE_SEP: ;
OD_FILE_TYPE: csv

# ANAC
OD_ANAC_DIR: open_data_anac
TENDER_MAIN_FILE: TENDER_NOTICE.csv      # INPUT the main dataset                

# CONFIGURATIONS
CONF_COLS_TYPE_FILE: conf_cols_type.json              # INPUT file with columns types for each CSV file (dataset)
CONF_COLS_STATS_FILE: conf_cols_stats.json            # INPUT file with columns to be included in stats for each CSV file (dataset)
CONF_COLS_FILTER_FILE: conf_cols_filter.json          # INPUT file with columns to be filtered by dataset

# STATS
OD_STATS_DIR: stats                                   # OUTPUT directory

# PLOTS
OD_PLOTS_DIR: plots                                   # OUTPUT directory

# ML
ML_RESULTS_DIR: ml_results
ML_PLOTS_DIR: ml_plots


